import { Router } from 'express';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { db } from '../db.js';
import { store } from '../storage.js';
import { config } from '../config.js';
import { adminAuth, signAdminJwt } from '../middleware.js';
import { scryptVerify, randomToken } from '../crypto-util.js';
import { rateLimit, clientIp } from '../ratelimit.js';
import { logger } from '../logger.js';
import { getOnlineCount } from '../ws.js';

/**
 * 管理后台:可看元数据/统计/封禁/删除密文,但绝不解密(没有密钥,解密在客户端)。
 * 登录:Basic 凭据(ADMIN_USER/ADMIN_PASSWORD,scrypt 校验)→ 颁发 12h admin JWT。
 */
export const adminRouter = Router();

/** 管理员登录 */
adminRouter.post('/login', async (req, res) => {
  const ip = clientIp(req);
  const r = rateLimit(`admin:login:${ip}`, 5, 10 * 60_000, 10 * 60_000);
  if (!r.ok) return res.status(429).json({ error: 'rate_limited', retryAfterSec: r.retryAfterSec });

  const { username, password } = req.body || {};
  if (String(username || '') !== config.adminUser) return res.status(401).json({ error: 'bad_credentials' });
  if (!scryptVerify(String(password || ''), config.adminPasswordHash)) {
    logger.warn('admin_login_failed', { ip });
    return res.status(401).json({ error: 'bad_credentials' });
  }
  const jwt = await signAdminJwt(config.adminUser);
  logger.info('admin_login', { ip });
  res.json({ ok: true, token: jwt });
});

adminRouter.use(adminAuth);

/** 登录后获取元数据(如管理员首次密码提示) */
adminRouter.get('/me', (_req, res) => {
  res.json({
    ok: true, user: config.adminUser,
    autoGeneratedPassword: config.adminPasswordPlain
      ? `首次自动生成密码位于 ${path.join(config.dataRoot, 'config', 'admin.cred')} (登录后请立即在服务器上修改)`
      : undefined,
  });
});

function audit(action: string, detail: string) {
  db.prepare('INSERT INTO admin_audit (ts, actor, action, detail) VALUES (?,?,?,?)')
    .run(Date.now(), config.adminUser, action, detail);
}

/** 概览统计 */
adminRouter.get('/stats', (_req, res) => {
  const stats = {
    users: (db.prepare('SELECT COUNT(*) AS c FROM users').get() as { c: number }).c,
    bannedUsers: (db.prepare('SELECT COUNT(*) AS c FROM users WHERE banned=1').get() as { c: number }).c,
    online: getOnlineCount(),
    tempRooms: (db.prepare('SELECT COUNT(*) AS c FROM temp_rooms').get() as { c: number }).c,
    activeTempRooms: (db.prepare('SELECT COUNT(*) AS c FROM temp_rooms WHERE status=\'active\' AND expires_at>?').get(Date.now()) as { c: number }).c,
    rooms: (db.prepare('SELECT COUNT(*) AS c FROM rooms').get() as { c: number }).c,
    messages: (db.prepare('SELECT COUNT(*) AS c FROM messages').get() as { c: number }).c,
    sessions: (db.prepare('SELECT COUNT(*) AS c FROM sessions').get() as { c: number }).c,
    uptimeSec: Math.round(process.uptime()),
    memUsedMB: Math.round(process.memoryUsage().rss / 1024 / 1024),
    cpuLoad: os.loadavg()[0],
    disk: store.diskUsageBytes(),
    diskFreeMB: Math.round(os.freemem() / 1024 / 1024),
    dbOk: health(),
    version: '1.0.0',
  };
  res.json({ ok: true, stats });
});

function health(): boolean {
  try { db.prepare('SELECT 1').get(); return true; } catch { return false; }
}

/** 用户列表(脱敏,不含任何聊天内容) */
adminRouter.get('/users', (req, res) => {
  const page = Math.max(Number(req.query.page || 1), 1);
  const limit = Math.min(Math.max(Number(req.query.limit || 50), 1), 200);
  const rows = db.prepare('SELECT id, phone_masked, email_masked, handle, created_at, banned, ban_reason, last_login_at FROM users ORDER BY id DESC LIMIT ? OFFSET ?')
    .all(limit, (page - 1) * limit);
  const total = (db.prepare('SELECT COUNT(*) AS c FROM users').get() as { c: number }).c;
  res.json({ ok: true, users: rows, total, page });
});

/** 封禁/解封用户 */
adminRouter.post('/users/:id/ban', (req, res) => {
  const id = Number(req.params.id);
  const ban = Boolean(req.body?.ban);
  if (!Number.isInteger(id) || id <= 0) return res.status(400).json({ error: 'bad_id' });
  db.prepare('UPDATE users SET banned=?, ban_reason=? WHERE id=?').run(ban ? 1 : 0, ban ? String(req.body?.reason || 'admin').slice(0, 200) : null, id);
  audit('user_ban', `user=${id} ban=${ban}`);
  logger.warn('admin_user_banned', { id, ban });
  res.json({ ok: true });
});

/** 删除账号 + 其私聊密文(密文按房间删除) */
adminRouter.delete('/users/:id', (req, res) => {
  const id = Number(req.params.id);
  if (!Number.isInteger(id) || id <= 0) return res.status(400).json({ error: 'bad_id' });
  const roomIds = (db.prepare('SELECT room_id FROM room_members WHERE user_id=?').all(id) as { room_id: string }[]).map((r) => r.room_id);
  const tx = db.transaction(() => {
    const paths = db.prepare('SELECT cipher_path FROM messages WHERE room_id IN (SELECT room_id FROM room_members WHERE user_id=?)').all(id) as { cipher_path: string }[];
    for (const p of paths) store.deleteCipher(p.cipher_path);
    db.prepare('DELETE FROM messages WHERE room_id IN (SELECT room_id FROM room_members WHERE user_id=?)').run(id);
    for (const rid of roomIds) {
      db.prepare('DELETE FROM room_keys WHERE room_id=?').run(rid);
      db.prepare('DELETE FROM room_members WHERE room_id=?').run(rid);
      db.prepare('DELETE FROM rooms WHERE id=? AND NOT EXISTS (SELECT 1 FROM room_members WHERE room_id=?)').run(rid, rid);
    }
    db.prepare('DELETE FROM user_keys WHERE user_id=?').run(id);
    db.prepare('DELETE FROM sessions WHERE user_id=?').run(id);
    db.prepare('DELETE FROM users WHERE id=?').run(id);
  });
  tx();
  audit('user_delete', `user=${id}`);
  logger.warn('admin_user_deleted', { id });
  res.json({ ok: true });
});

/** 临时房间列表(元数据) */
adminRouter.get('/temp-rooms', (req, res) => {
  const page = Math.max(Number(req.query.page || 1), 1);
  const limit = Math.min(Math.max(Number(req.query.limit || 50), 1), 200);
  const rows = db.prepare('SELECT id, created_at, expires_at, msg_count, status, last_activity FROM temp_rooms ORDER BY created_at DESC LIMIT ? OFFSET ?')
    .all(limit, (page - 1) * limit);
  const total = (db.prepare('SELECT COUNT(*) AS c FROM temp_rooms').get() as { c: number }).c;
  res.json({ ok: true, rooms: rows, total, page });
});

/** 封禁临时房间(禁止新消息,保留归档) */
adminRouter.post('/temp-rooms/:id/ban', (req, res) => {
  const id = String(req.params.id);
  const ban = Boolean(req.body?.ban);
  db.prepare('UPDATE temp_rooms SET status=? WHERE id=?').run(ban ? 'banned' : 'active', id);
  audit('temp_room_ban', `room=${id} ban=${ban}`);
  logger.warn('admin_temp_room_banned', { id, ban });
  res.json({ ok: true });
});

/** 删除临时房间全部密文(彻底删除) */
adminRouter.delete('/temp-rooms/:id', (req, res) => {
  const id = String(req.params.id);
  const paths = db.prepare('SELECT cipher_path FROM messages WHERE room_id=?').all(id) as { cipher_path: string }[];
  const tx = db.transaction(() => {
    for (const p of paths) store.deleteCipher(p.cipher_path);
    db.prepare('DELETE FROM messages WHERE room_id=?').run(id);
    db.prepare('DELETE FROM temp_rooms WHERE id=?').run(id);
  });
  tx();
  audit('temp_room_delete', `room=${id} messages=${paths.length}`);
  logger.warn('admin_temp_room_deleted', { id, messages: paths.length });
  res.json({ ok: true });
});

/** 消息元数据(按房间;绝不返回密文内容) */
adminRouter.get('/rooms/:id/messages', (req, res) => {
  const id = String(req.params.id);
  const limit = Math.min(Math.max(Number(req.query.limit || 100), 1), 500);
  const rows = db.prepare('SELECT id, seq, kind, sender_user_id, sender_anon, cipher_path, ts, read_by FROM messages WHERE room_id=? ORDER BY seq DESC LIMIT ?')
    .all(id, limit);
  res.json({ ok: true, messages: rows });
});

/** 错误日志尾部 */
adminRouter.get('/logs', (req, res) => {
  const lines = Math.min(Math.max(Number(req.query.lines || 100), 1), 500);
  const logDir = path.join(config.dataRoot, 'logs');
  const files = fs.readdirSync(logDir).filter((f) => f.startsWith('error.')).sort().reverse();
  const out: string[] = [];
  for (const f of files.slice(0, 3)) {
    try {
      const content = fs.readFileSync(path.join(logDir, f), 'utf8').trim().split('\n');
      out.push(`--- ${f} ---`, ...content.slice(-lines));
    } catch { /* ignore */ }
  }
  res.json({ ok: true, logs: out });
});

/** 管理员操作审计日志 */
adminRouter.get('/audit', (req, res) => {
  const rows = db.prepare('SELECT ts, actor, action, detail FROM admin_audit ORDER BY id DESC LIMIT 100').all();
  res.json({ ok: true, audit: rows });
});

/** 轮换管理员密码(写回 config/env.json 需管理员自行操作;这里提供工具) */
adminRouter.post('/rotate-password', async (req, res) => {
  const { newPassword } = req.body || {};
  if (typeof newPassword !== 'string' || newPassword.length < 12) {
    return res.status(400).json({ error: 'password_too_short' });
  }
  // 生成新的 .env 片段,提示管理员在服务器配置
  const envPath = path.join(process.cwd(), 'config', 'env.json');
  let env: Record<string, string> = {};
  try { env = JSON.parse(fs.readFileSync(envPath, 'utf8')); } catch { /* ignore */ }
  env.ADMIN_PASSWORD = newPassword;
  fs.writeFileSync(envPath, JSON.stringify(env, null, 2), { mode: 0o600 });
  audit('admin_rotate_password', 'password rotated (config/env.json)');
  res.json({ ok: true, note: 'updated config/env.json; restart service to apply' });
});

export { randomToken };
